# Generated by Django 2.0.2 on 2018-03-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_auto_20180325_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animeId', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=500)),
                ('animeType', models.CharField(max_length=500)),
                ('rating', models.FloatField()),
                ('members', models.IntegerField()),
            ],
        ),
    ]
