# Generated by Django 2.0.2 on 2018-03-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_anime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='animeId',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='members',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.CharField(max_length=500),
        ),
    ]
